- name: configure mysql server
  hosts: db
  become: yes
  tasks:
  - name: installing mysql server
    ansible.builtin.dnf:
      name: mysql
      state: latest
  
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
      
